% -------------------------------------------------------------------
%  Generated by MATLAB on 9-Jul-2022 12:45:21
%  MATLAB version: 9.9.0.1467703 (R2020b)
% -------------------------------------------------------------------
                                   

A = Simulink.Signal;
A.CoderInfo.StorageClass = 'Auto';
A.Description = 'BatteryCurrentA';
A.DataType = 'single';
A.Min = [];
A.Max = [];
A.DocUnits = 'A';
A.Dimensions = -1;
A.DimensionsMode = 'auto';
A.Complexity = 'auto';
A.SampleTime = -1;
A.InitialValue = '';

Charge = Simulink.Signal;
Charge.CoderInfo.StorageClass = 'Auto';
Charge.Description = 'BatteryCharge';
Charge.DataType = 'single';
Charge.Min = [];
Charge.Max = [];
Charge.DocUnits = 'A*hr';
Charge.Dimensions = -1;
Charge.DimensionsMode = 'auto';
Charge.Complexity = 'auto';
Charge.SampleTime = -1;
Charge.InitialValue = '';

Power = Simulink.Signal;
Power.CoderInfo.StorageClass = 'Auto';
Power.Description = 'BatteryPower';
Power.DataType = 'single';
Power.Min = [];
Power.Max = [];
Power.DocUnits = 'W';
Power.Dimensions = -1;
Power.DimensionsMode = 'auto';
Power.Complexity = 'auto';
Power.SampleTime = -1;
Power.InitialValue = '';

PowerLoss = Simulink.Signal;
PowerLoss.CoderInfo.StorageClass = 'Auto';
PowerLoss.Description = 'BatteryLoss';
PowerLoss.DataType = 'single';
PowerLoss.Min = [];
PowerLoss.Max = [];
PowerLoss.DocUnits = 'W';
PowerLoss.Dimensions = -1;
PowerLoss.DimensionsMode = 'auto';
PowerLoss.Complexity = 'auto';
PowerLoss.SampleTime = -1;
PowerLoss.InitialValue = '';

V = Simulink.Signal;
V.CoderInfo.StorageClass = 'Auto';
V.Description = 'BatteryV';
V.DataType = 'single';
V.Min = [];
V.Max = [];
V.DocUnits = 'V';
V.Dimensions = -1;
V.DimensionsMode = 'auto';
V.Complexity = 'auto';
V.SampleTime = -1;
V.InitialValue = '';

